name: Caretaker

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

#
# Needs to be updted on a release too
#

jobs:
  caretaker:
    runs-on: ubuntu-latest
    name: Caretaker
    steps:
      - name: Check our repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Caretaker
        id: caretaker
        uses: ActionsToolbox/caretaker-action@master
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-push-user-email: ${{ secrets.GPG_EMAIL }}
